import type { Locale } from "@/i18n/config";

export const architectureByLocale: Record<Locale, {
  payrithm: { title: string; boxes: Array<[string, string]> };
  tenderwise: { title: string; boxes: Array<[string, string]> };
}> = {
  en: {
    payrithm: { title: "Payrithm architecture", boxes: [["React frontend", "Dashboards, imports, configuration and collection workflows"], ["FastAPI application", "Authentication, validation, business rules and prediction APIs"], ["PostgreSQL", "Tenants, invoices, customers, predictions and model records"], ["Celery workers", "CSV imports, model training and scheduled processing"], ["Redis", "Job queue and worker coordination"], ["ML pipeline", "Feature generation, validation, training and monitoring"]] },
    tenderwise: { title: "TenderWise architecture", boxes: [["Shared Nginx edge", "HTTPS, Certbot, public host routing, and reverse proxy headers"], ["React/Vite web", "Multilingual application shell, dashboard, profiles, billing, and bid workspaces"], ["FastAPI API", "Auth, workspaces, TED data, scoring, decisions, audit, and billing webhooks"], ["PostgreSQL + pgvector", "Workspaces, notices, canonical TED versions, scoring results, usage, and audit state"], ["Redis + Celery", "Job queue, retries, worker heartbeat, digests, email, and AI generation tasks"], ["TED and AI providers", "TED Search ingestion plus optional Ollama or OpenAI-compatible tender briefs"]] },
  },
  ca: {
    payrithm: { title: "Arquitectura de Payrithm", boxes: [["Frontend React", "Taulers, importacions, configuració i fluxos de cobrament"], ["Aplicació FastAPI", "Autenticació, validació, regles de negoci i APIs de predicció"], ["PostgreSQL", "Tenants, factures, clients, prediccions i registres de models"], ["Workers Celery", "Importacions CSV, entrenament de models i processament programat"], ["Redis", "Cua de tasques i coordinació de workers"], ["Pipeline ML", "Generació de variables, validació, entrenament i monitoratge"]] },
    tenderwise: { title: "Arquitectura de TenderWise", boxes: [["Capa Nginx compartida", "HTTPS, Certbot, routing de hosts públics i capçaleres de reverse proxy"], ["Web React/Vite", "Shell multilingüe, tauler, perfils, facturació i espais de treball d’ofertes"], ["API FastAPI", "Autenticació, workspaces, dades TED, scoring, decisions, auditoria i webhooks de facturació"], ["PostgreSQL + pgvector", "Workspaces, anuncis, versions TED canòniques, resultats de scoring, ús i estat d’auditoria"], ["Redis + Celery", "Cua de tasques, reintents, heartbeat de workers, resums, correu i tasques d’IA"], ["TED i proveïdors d’IA", "Ingestió de TED Search i resums opcionals amb Ollama o APIs compatibles amb OpenAI"]] },
  },
  es: {
    payrithm: { title: "Arquitectura de Payrithm", boxes: [["Frontend React", "Paneles, importaciones, configuración y flujos de cobro"], ["Aplicación FastAPI", "Autenticación, validación, reglas de negocio y APIs de predicción"], ["PostgreSQL", "Tenants, facturas, clientes, predicciones y registros de modelos"], ["Workers Celery", "Importaciones CSV, entrenamiento de modelos y procesamiento programado"], ["Redis", "Cola de tareas y coordinación de workers"], ["Pipeline ML", "Generación de variables, validación, entrenamiento y monitorización"]] },
    tenderwise: { title: "Arquitectura de TenderWise", boxes: [["Capa Nginx compartida", "HTTPS, Certbot, routing de hosts públicos y cabeceras de reverse proxy"], ["Web React/Vite", "Shell multilingüe, panel, perfiles, facturación y espacios de trabajo de ofertas"], ["API FastAPI", "Autenticación, workspaces, datos TED, scoring, decisiones, auditoría y webhooks de facturación"], ["PostgreSQL + pgvector", "Workspaces, anuncios, versiones TED canónicas, resultados de scoring, uso y estado de auditoría"], ["Redis + Celery", "Cola de tareas, reintentos, heartbeat de workers, resúmenes, correo y tareas de IA"], ["TED y proveedores de IA", "Ingesta de TED Search y resúmenes opcionales con Ollama o APIs compatibles con OpenAI"]] },
  },
  de: {
    payrithm: { title: "Payrithm-Architektur", boxes: [["React-Frontend", "Dashboards, Importe, Konfiguration und Inkasso-Workflows"], ["FastAPI-Anwendung", "Authentifizierung, Validierung, Geschäftsregeln und Prognose-APIs"], ["PostgreSQL", "Mandanten, Rechnungen, Kunden, Prognosen und Modellaufzeichnungen"], ["Celery-Worker", "CSV-Importe, Modelltraining und geplante Verarbeitung"], ["Redis", "Job-Queue und Worker-Koordination"], ["ML-Pipeline", "Feature-Erzeugung, Validierung, Training und Monitoring"]] },
    tenderwise: { title: "TenderWise-Architektur", boxes: [["Gemeinsame Nginx-Schicht", "HTTPS, Certbot, öffentliches Host-Routing und Reverse-Proxy-Header"], ["React/Vite-Web", "Mehrsprachige Oberfläche, Dashboard, Profile, Abrechnung und Angebotsarbeitsbereiche"], ["FastAPI-API", "Authentifizierung, Workspaces, TED-Daten, Scoring, Entscheidungen, Audit und Billing-Webhooks"], ["PostgreSQL + pgvector", "Workspaces, Bekanntmachungen, kanonische TED-Versionen, Scoring-Ergebnisse, Nutzung und Audit-Status"], ["Redis + Celery", "Job-Queue, Wiederholungen, Worker-Heartbeat, Digests, E-Mail und KI-Aufgaben"], ["TED- und KI-Anbieter", "TED-Search-Ingestion sowie optionale Briefings mit Ollama oder OpenAI-kompatiblen APIs"]] },
  },
};
