import type { Locale } from "@/i18n/config";

export interface ExperienceItem {
  period: string;
  role: string;
  company: string;
  location: string;
  achievements: string[];
}

export const experienceByLocale: Record<Locale, ExperienceItem[]> = {
  en: [
    { period: "June 2025 — Present", role: "Software Developer", company: "Adasa Systems", location: "El Prat de Llobregat, Spain", achievements: ["Implement backend functionality using Python and an IoT platform.", "Integrate API, FTP, hydrological, meteorological, raster, and ensemble geographical data.", "Build scheduled ingestion workflows with custom schedulers and Apache Airflow.", "Store and expose operational data through PostgreSQL, PostGIS, GeoServer, and APIs."] },
    { period: "January 2023 — Present", role: "Data Scientist", company: "Adasa Systems", location: "El Prat de Llobregat, Spain", achievements: ["Developed machine-learning models for real-time water-treatment and dam time-series data.", "Built a contamination-event detector with more than 80% detection capability.", "Used SHAP to interpret model predictions.", "Created Streamlit and FastAPI tools for configuring, migrating, and visualizing models.", "Developed a RAG application with ChromaDB, LangChain, Ollama, FastAPI, and React."] },
    { period: "June 2022 — January 2023", role: "Data Scientist", company: "HP through Between Technology", location: "Sant Cugat del Vallès, Spain", achievements: ["Automated database ETL processes with Python and Databricks.", "Analyzed repair, printing, customer-service, and review data.", "Automated recurring reporting workflows with Python and PostgreSQL."] },
    { period: "January 2019 — June 2022", role: "Data Scientist and Researcher", company: "Institute of Materials Science of Barcelona", location: "Cerdanyola del Vallès, Spain", achievements: ["Led high-throughput experimentation and data-driven material-discovery work.", "Automated experimental hardware and data acquisition with Python.", "Developed machine-learning models for experimental optimization and prediction."] },
  ],
  ca: [
    { period: "Juny 2025 — Actualitat", role: "Desenvolupador de programari", company: "Adasa Systems", location: "El Prat de Llobregat, Espanya", achievements: ["Implemento funcionalitat backend amb Python i una plataforma IoT.", "Integro dades d’API, FTP, hidrològiques, meteorològiques, ràster i conjunts geogràfics.", "Construeixo fluxos d’ingestió programats amb planificadors propis i Apache Airflow.", "Emmagatzemo i exposo dades operatives amb PostgreSQL, PostGIS, GeoServer i APIs."] },
    { period: "Gener 2023 — Actualitat", role: "Científic de dades", company: "Adasa Systems", location: "El Prat de Llobregat, Espanya", achievements: ["He desenvolupat models de machine learning per a sèries temporals en temps real de tractament d’aigua i preses.", "He construït un detector d’esdeveniments de contaminació amb més del 80% de capacitat de detecció.", "He utilitzat SHAP per interpretar prediccions dels models.", "He creat eines amb Streamlit i FastAPI per configurar, migrar i visualitzar models.", "He desenvolupat una aplicació RAG amb ChromaDB, LangChain, Ollama, FastAPI i React."] },
    { period: "Juny 2022 — Gener 2023", role: "Científic de dades", company: "HP mitjançant Between Technology", location: "Sant Cugat del Vallès, Espanya", achievements: ["Vaig automatitzar processos ETL de bases de dades amb Python i Databricks.", "Vaig analitzar dades de reparacions, impressió, servei al client i ressenyes.", "Vaig automatitzar informes recurrents amb Python i PostgreSQL."] },
    { period: "Gener 2019 — Juny 2022", role: "Científic de dades i investigador", company: "Institut de Ciència de Materials de Barcelona", location: "Cerdanyola del Vallès, Espanya", achievements: ["Vaig liderar experimentació d’alt rendiment i descobriment de materials basat en dades.", "Vaig automatitzar maquinari experimental i adquisició de dades amb Python.", "Vaig desenvolupar models de machine learning per a optimització i predicció experimental."] },
  ],
  es: [
    { period: "Junio 2025 — Actualidad", role: "Desarrollador de software", company: "Adasa Systems", location: "El Prat de Llobregat, España", achievements: ["Implemento funcionalidad backend con Python y una plataforma IoT.", "Integro datos de API, FTP, hidrológicos, meteorológicos, ráster y conjuntos geográficos.", "Construyo flujos de ingesta programados con planificadores propios y Apache Airflow.", "Almaceno y expongo datos operativos mediante PostgreSQL, PostGIS, GeoServer y APIs."] },
    { period: "Enero 2023 — Actualidad", role: "Científico de datos", company: "Adasa Systems", location: "El Prat de Llobregat, España", achievements: ["He desarrollado modelos de machine learning para series temporales en tiempo real de tratamiento de agua y presas.", "He construido un detector de eventos de contaminación con más del 80% de capacidad de detección.", "He utilizado SHAP para interpretar predicciones de los modelos.", "He creado herramientas con Streamlit y FastAPI para configurar, migrar y visualizar modelos.", "He desarrollado una aplicación RAG con ChromaDB, LangChain, Ollama, FastAPI y React."] },
    { period: "Junio 2022 — Enero 2023", role: "Científico de datos", company: "HP a través de Between Technology", location: "Sant Cugat del Vallès, España", achievements: ["Automaticé procesos ETL de bases de datos con Python y Databricks.", "Analicé datos de reparaciones, impresión, atención al cliente y reseñas.", "Automaticé flujos de informes recurrentes con Python y PostgreSQL."] },
    { period: "Enero 2019 — Junio 2022", role: "Científico de datos e investigador", company: "Instituto de Ciencia de Materiales de Barcelona", location: "Cerdanyola del Vallès, España", achievements: ["Lideré experimentación de alto rendimiento y descubrimiento de materiales basado en datos.", "Automaticé hardware experimental y adquisición de datos con Python.", "Desarrollé modelos de machine learning para optimización y predicción experimental."] },
  ],
  de: [
    { period: "Juni 2025 — Heute", role: "Softwareentwickler", company: "Adasa Systems", location: "El Prat de Llobregat, Spanien", achievements: ["Backend-Funktionalität mit Python und einer IoT-Plattform implementieren.", "API-, FTP-, hydrologische, meteorologische, Raster- und geografische Ensemble-Daten integrieren.", "Zeitgesteuerte Ingestion-Workflows mit eigenen Schedulern und Apache Airflow entwickeln.", "Betriebsdaten mit PostgreSQL, PostGIS, GeoServer und APIs speichern und bereitstellen."] },
    { period: "Januar 2023 — Heute", role: "Data Scientist", company: "Adasa Systems", location: "El Prat de Llobregat, Spanien", achievements: ["Machine-Learning-Modelle für Echtzeit-Zeitreihen aus Wasseraufbereitung und Staudämmen entwickelt.", "Einen Kontaminationsereignis-Detektor mit mehr als 80 % Erkennungsleistung entwickelt.", "SHAP zur Interpretation von Modellvorhersagen eingesetzt.", "Streamlit- und FastAPI-Werkzeuge für Konfiguration, Migration und Visualisierung von Modellen erstellt.", "Eine RAG-Anwendung mit ChromaDB, LangChain, Ollama, FastAPI und React entwickelt."] },
    { period: "Juni 2022 — Januar 2023", role: "Data Scientist", company: "HP über Between Technology", location: "Sant Cugat del Vallès, Spanien", achievements: ["Datenbank-ETL-Prozesse mit Python und Databricks automatisiert.", "Reparatur-, Druck-, Kundendienst- und Bewertungsdaten analysiert.", "Wiederkehrende Reporting-Workflows mit Python und PostgreSQL automatisiert."] },
    { period: "Januar 2019 — Juni 2022", role: "Data Scientist und Forscher", company: "Institut für Materialwissenschaften Barcelona", location: "Cerdanyola del Vallès, Spanien", achievements: ["Hochdurchsatzexperimente und datengetriebene Materialentdeckung geleitet.", "Experimentelle Hardware und Datenerfassung mit Python automatisiert.", "Machine-Learning-Modelle für experimentelle Optimierung und Vorhersage entwickelt."] },
  ],
};
